Feature/userview
wecode-bootcamp-korea/31-1st-SITWITH-backend pull request #6
Opened 2022-03-31 04:11 UTC by angrybirdpark

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원가입/로그인 기능 구현
- products.models : Image class에 color(FK) 컬럼 추가 (product_id, color_id가 둘다 필요한 시디즈 상품 특성 반영)
- carts.models : quantity 부분에 default = 0 추가 (추후 view 작성시 get or created crud를 이용하기 위함)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입 데이터 처리
- 조건문과 정규식을 이용해서 username, password, email 유효성 검사 진행
  - email의 경우, 기입하지 않은 경우도 가입이 허용됨
  - 정규식을 만족하지 않는 경우, 각각의 에러메세지 도출
- 이미 가입한 username, email이 있을 시 에러메세지 도출
- bcrypt를 이용해 password hash 작업 후 db에 username, hashed_password, email 저장

2. 로그인 데이터 처리 (예시 - 백엔드)
- bcrypt를 이용한 password 검증 작업. 실패 시, 에러메세지 도출
- jwt를 이용해 access_token 생성 후, JsonResponse로 토큰 전달
- User에 만족하는 username이 없을 시, 에러메세지 도출

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 에러메세지가 도출되는 경우를 여러 방면에서 생각하게 되었습니다.
- westagram 이후에 다시 회원가입/로그인을 작성하게 되면서 회원가입/로그인 로직에 대해 이해를 더 잘 할 수 있게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-03-31 05:29 UTC, angrybirdpark commented
슬랙으로 주셨던 피드백 확인 후, 수정완료해서 commit 올렸습니다!

2022-03-31 07:34 UTC, jamessoun93 requested changes

2022-03-31 07:34 UTC, jamessoun93 commented on cores/decorator.py
> +            request.user = user
이 부분 정확히 뭘하는건지 이해하신 내용 바탕으로 설명해주세요.

2022-03-31 07:34 UTC, jamessoun93 commented on cores/decorator.py
> +            return JsonResponse({'Message' : 'Invalid user'}, status=400)
json body key값 소문자로 통일해주세요.

2022-03-31 07:34 UTC, jamessoun93 commented on users/validator.py
> +            raise ValidationError("Invalid email")
함수명은 동사가 먼저올 수 있도록 해주세요.
```suggestion
def validate_username(username):
    if not re.match(REGEX_USERNAME, username):
        raise ValidationError("Invalid username")

def validate_password(password):
    if not re.match(REGEX_PASSWORD, password):
        raise ValidationError("Invalid password")
    
def validate_email(email):
    if email == "":
        pass
    else:
        if not re.match(REGEX_EMAIL, email):
            raise ValidationError("Invalid email")
```

2022-03-31 07:34 UTC, jamessoun93 commented on users/validator.py
> +        pass
이 부분 설명한번 해주시겠어요?

2022-03-31 07:34 UTC, jamessoun93 commented on users/views.py
> +                return JsonResponse({'message' : 'Email already exists'}, status=401)
회원가입을 할때 이미 존재하는 resource라는 의미의 response status code로 401은 적당하지 않아보입니다. 뭐가 좋을까요?!

2022-03-31 07:34 UTC, jamessoun93 commented on users/views.py
> +            access_token = jwt.encode({'id':user.id}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
이 부분은 제가 31기 백엔드 슬랙방에 올려드린 고민해보면 좋을 부분 참고하셔서 어떤 내용 추가하면 좋을지 생각해보세요!

2022-03-31 07:38 UTC, angrybirdpark commented on cores/decorator.py
> +            request.user = user
user         = User.objects.get(id = payload['id']) 의 경우,
데코레이터에서 jwt를 통해 decode한 값들 중에서 key를 id로 하는 값을 불러와 User table에서 id와 일치하는 것을 user로 저장합니다.
그리고 def post(self, request) 아래에 적용하기 위해 request.user = user로 변수 저장을 해줬습니다.

2022-03-31 07:47 UTC, angrybirdpark commented on users/validator.py
> +        pass
시디즈 회원가입 시, 이메일은 작성하지 않아도 가입이 되었습니다.
그래서 email이 없는 경우 따로 validate를 진행하지 않았습니다.

추가로, view에서 이메일 존재 여부를 검증하는 곳도 해당 작업이 필요하여 수정 후 올리겠습니다..!

2022-03-31 07:55 UTC, angrybirdpark commented on users/views.py
> +                return JsonResponse({'message' : 'Email already exists'}, status=401)
현재 상태와 충돌돼서 오류가 나는 것으로 409 conflict 에러로 수정하였습니다.

2022-03-31 07:57 UTC, angrybirdpark commented on users/views.py
> +            access_token = jwt.encode({'id':user.id}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
해당 id로 로그인 시, 만료 시간이 따로 없는 문제가 생기기 떄문에 exp 부분을 추가해서 수정하겠습니다!

2022-03-31 08:09 UTC, angrybirdpark commented on cores/decorator.py
> +            return JsonResponse({'Message' : 'Invalid user'}, status=400)
수정 완료했습니다!

2022-03-31 08:10 UTC, angrybirdpark commented on users/validator.py
> +            raise ValidationError("Invalid email")
수정 완료했습니다.

2022-03-31 08:40 UTC, jamessoun93 commented on cores/decorator.py
> +            request.user = user
과정은 잘 이해하고 계신데 제 질문의 의도는 데코레이터를 통해 request 객체라는 박스에 user 객체를 담아 post 메소드에서 활용할 수 있게 넘겨주는 플로우를 이해하고 계신지 확인하고자하는 의도였습니다.

이 부분이 잘 이해되신다면 다행이구요 👍

2022-03-31 08:40 UTC, jamessoun93 commented on users/validator.py
> +        pass
이 부분은 기다려야하는거죠?

2022-03-31 08:53 UTC, angrybirdpark commented on users/validator.py
> +        pass
자리에서 말씀해주셨던 것 처럼, email이 빈 값인 경우를 배제해서 기능 구현 완료했습니다..!

2022-04-01 01:47 UTC, jamessoun93 approved these changes
LGTM

2022-04-01 01:48 UTC, merged