[ADD]Make Products View & urls
wecode-bootcamp-korea/31-1st-SITWITH-backend pull request #8
Opened 2022-04-01 09:12 UTC by JeongHyeon-01

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- Products 정보 를 카테고리 및 상세페이지, 서칭할 정보 받아오기

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카테고리, 전체, 제품명, 제품명 +컬러 호출시 해당 카테고리에 대한 정보 호출
https://deadpan-tulip-2da.notion.site/602f625668a24367ba4f01e4a5dbef58 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- get으로만 요청을 받았을때 쿼리를 통해 url에 있는 정보를 가져올수 있게 되었습니다
- 여러가지를 쉘로 쳐보면서 더욱 효과적인 코딩을 할수는 없을까 고민하였습니다.
 
<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.

2022-04-02 08:09 UTC, JeongHyeon-01 commented
<구현사항>
url 구조 변경 

- /products  \전체 상품 보기
- /products?category=1&2 \카테고리별 확인
- products/<int> \상품검색
- products/<int>?color=<int> \ 색상별 검색
-
views 구조변경
기존 urlparameter 구조에서 쿼리스트링 가능한 형태로 변경 및 한눈에 보기 편하게 변경

2022-04-03 07:52 UTC, jamessoun93 requested changes

2022-04-03 07:52 UTC, jamessoun93 commented on products/views.py
> +            product_data = Product.objects.all()
조건문을 활용해서 분기처리를 할때, 가능하다면 else를 굳이 사용하지 않아도 되는 형태로 만들어주시는게 좋습니다. 몇가지 적어드릴테니 활용해서 리팩토링 해보세요.

1. Product.objects.filter() 문에 조건이 따로 없으면 사실상 all() 가 마찬가지로 작동하게 됩니다.
2. Q객체를 활용하여 조건들을 만들어준다고 쳤을때 Q객체가 비어있으면 all()과 마찬가지라는 뜻이죠. (`Product.objects.filter(Q())`)
3. if문 하나만 가지고 조건에 따라 Q() 객체를 비워둘지, 안에 조건을 추가할지 결정하고 결과적으로 if문 하나와 filter문 하나만 가지고 Product 모델에 대한 필터문을 생성해보세요.

2022-04-03 07:52 UTC, jamessoun93 commented on products/views.py
> +            return JsonResponse({"message":"Category does not exist"}, status = 400)
QuerySet의 경우 조건에 해당하는 객체들이 존재하지 않을 시 빈 리스트의 형태로 반환되게 되는데, 사실 필터 조건에 해당하는 객체가 존재하지 않는다고 해서 요청 자체가 잘못되었다는 400 status를 반환해주는건 맞지 않다고 생각합니다. 없으면 없는대로 빈 리스트가 반환되면 되는것이죠.

2022-04-03 07:52 UTC, jamessoun93 commented on products/views.py
> +            })
이 부분을 통째로 list comprehension의 형태로 변경해보세요.

2022-04-03 07:52 UTC, jamessoun93 commented on products/views.py
> +        return JsonResponse({"message":"Success", "result":result}, status = 200)
200으로 충분히 해당 요청이 성공적으로 처리되었다는것을 알 수 있으니 message 는 불필요합니다.

2022-04-03 07:52 UTC, jamessoun93 commented on products/views.py
> +        product_data = Product.objects.filter(id=product_id)
해당 product_id를 가진 Product 객체를 한개만 존재할텐데 filter 대신 get이 더 적합해보입니다.

2022-04-03 07:52 UTC, jamessoun93 commented on products/views.py
> +            return JsonResponse({"message":"Product does not exist"}, status = 400)
위와 같이 수정하면 해당 if문도 불필요하게 되겠죠.

2022-04-03 07:52 UTC, jamessoun93 commented on products/views.py
> +        for product in product_data:
product가 하나뿐이라 반복문은 필요하지 않습니다.

2022-04-03 07:52 UTC, jamessoun93 commented on products/views.py
> +
여기도 위와같이 else없이 if문을 하나로 필터조건을 만들어줄 수 있도록 수정해보세요.

2022-04-03 12:55 UTC, JeongHyeon-01 commented
---04.03 수정사항--
- Q 를 사용해서 변경완료
- productlistview에서 smartsearch 가능하게 끔 수정

2022-04-03 12:57 UTC, JeongHyeon-01 commented on products/views.py
> +            product_data = Product.objects.all()
Q객체를 이용하여 수정완료

2022-04-03 12:57 UTC, JeongHyeon-01 commented on products/views.py
> +            })
완료

2022-04-03 12:57 UTC, JeongHyeon-01 commented on products/views.py
> +        return JsonResponse({"message":"Success", "result":result}, status = 200)
삭제완료

2022-04-03 12:57 UTC, JeongHyeon-01 commented on products/views.py
> +        for product in product_data:
완료!

2022-04-03 12:57 UTC, JeongHyeon-01 commented on products/views.py
> +            return JsonResponse({"message":"Category does not exist"}, status = 400)
빈리스트 반환 완료

2022-04-03 12:58 UTC, JeongHyeon-01 commented on products/views.py
> +        product_data = Product.objects.filter(id=product_id)
ProductColor 라는 중간테이블을 불러와서 문제해결 했습니다.

2022-04-03 12:59 UTC, JeongHyeon-01 commented on products/views.py
> +
완료했습니다!

2022-04-04 02:29 UTC, jamessoun93 requested changes

2022-04-04 02:29 UTC, jamessoun93 commented on products/views.py
> +        price_lower_range  = request.GET.get('pricelower',0)
```suggestion
        max_price  = request.GET.get('max_price', 100000000)
        min_price  = request.GET.get('min_price', 0)
```

2022-04-04 02:29 UTC, jamessoun93 commented on products/views.py
> +        if color :
```suggestion
        if color:
```

2022-04-04 02:29 UTC, jamessoun93 commented on products/views.py
> +        color= request.GET.getlist('color',None)
값이 리스트로 들어올 수 있는 변수는 꼭 복수형으로 선언해주세요.

```suggestion
        categories = request.GET.getlist('category', None)
        colors = request.GET.getlist('color',None)
```

2022-04-04 02:29 UTC, jamessoun93 commented on products/views.py
> +            q &= Q(product__name__istartswith = product)
startswith은 무조건 해당 조건으로 시작해야한다는 단점이 있어서 조금 더 포괄적인 contains를 사용하시는게 어떨까요? 이 부분은 검색 기능 기획에 따라 정해주시면 될 것 같습니다.

2022-04-04 02:29 UTC, jamessoun93 commented on products/views.py
> +            q &= Q(color__name__in = (color))
소괄호는 불필요합니다.
```suggestion
            q &= Q(color__name__in = color)
```

2022-04-04 02:29 UTC, jamessoun93 commented on products/views.py
> +
빈줄은 한줄이면 충분합니다.

2022-04-04 02:31 UTC, jamessoun93 requested changes

2022-04-04 02:31 UTC, jamessoun93 commented on products/views.py
> +        }for product in product_data]
이렇게 하면 해당 제품에 존재하는 컬러마다 product.name 과 product.price는 불필요하게 중복될텐데 어떻게 변경하면 좋을지 고민해보셨으면 좋겠네요.

2022-04-04 03:06 UTC, JeongHyeon-01 commented
인덴트 수정 밎 변수 &추가 보완사항 반영해서 수정하였습니다

2022-04-04 07:09 UTC, JeongHyeon-01 commented
이름의 경우 이름+컬러 식으로 나오는게 시디즈 페이지와 동일할듯해서 수정하였습니다

2022-04-05 06:26 UTC, jamessoun93 requested changes

2022-04-05 06:26 UTC, jamessoun93 commented on products/views.py
> +                    "image" : [image.image_url for image in Image.objects.filter(product_color_id=color.id, sequence=1)][0]
들여쓰기가 4칸 이상인 것 같은데 확인해주세요.

2022-04-05 06:26 UTC, jamessoun93 commented on products/views.py
> +        q &= Q (product__price__range = (min_price, max_price))
Q객체를 처음 만들어주는 시점에 바로 조건을 넣어서 만들어주면 되겠죠?
```suggestion
        q = Q(product__price__range = (min_price, max_price))

        if categories:
            q &= Q(product__category_id__in = categories)

        if product:
            q &= Q(product__name__icontains = product)
                       
        if colors:
            q &= Q(color__name__in = colors)
```

2022-04-05 06:26 UTC, jamessoun93 commented on products/views.py
> +        products = Product.objects.all()
데이터베이스에 제품에 몇억개 단위로 저장되어 있을때 이렇게 요청마다 전부 가져오게되면 안되겠죠?
어떤 부분이 추가되어야 할까요?

2022-04-05 06:40 UTC, JeongHyeon-01 commented on products/views.py
> +        products = Product.objects.all()
반영후 수정완료

2022-04-05 06:42 UTC, JeongHyeon-01 commented
수정사항 반영해서 수정하였습니다!

2022-04-05 07:56 UTC, merged