장바구니 기능 구현
wecode-bootcamp-korea/31-1st-SITWITH-backend pull request #9
Opened 2022-04-05 05:04 UTC by angrybirdpark

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니 post, get, patch, delete 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품상세페이지에서 장바구니 버튼을 이용한 등록 기능 구현
- 데코레이터를 이용해 토큰을 받아 유저를 식별한다.
- 해당 상품의 색상, 수량값을 장바구니 DB에 저장한다.
- 이미 해당 상품의 색상이 DB에 등록되어있으면 수량값을 더해준다.
- 수량은 재고보다 많게 설정할 수 없으며, 최소값은 1이다.

2. get method 기능 구현
- 데코레이터를 이용해 토큰을 받아 유저를 식별한다.
- 해당 유저의 장바구니 목록의 정보를 보내준다.

3. 장바구니페이지에서 장바구니 수량선택을 이용한 수량 수정 기능 구현
- patch method를 이용해 수량값만 변경하여 DB에 업데이트
- 수량은 재고보다 많게 설정할 수 없으며, 최소값은 1이다.

4. 장바구니페이지에서 장바구니 삭제버튼, 선택삭제버튼을 이용한 장바구니 삭제 기능 구현
- delete method를 이용해 DB에서 삭제
- Cart id를 리스트 형태로 프론트엔드에서 받아와서 각각을 삭제하도록 기능 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 다양한 method를 사용하게 되면서 새로 써보는 method를 공부하게 되었고 각 특성을 필요할 때 사용할 수 있게 되었습니다.
- REST API에 대해 적용해보고 Restful하게 만드려면 어떻게해야하는지 고민하게 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
- patch, delete의 경우 쿼리 파라미터로 작성했는데, 이 부분에 대해 body로 받는것과 비교해서
효율적 측면의 차이가 있는 것인지 궁금합니다.

2022-04-05 06:50 UTC, jamessoun93 requested changes

2022-04-05 06:50 UTC, jamessoun93 commented on carts/views.py
> +            product_color_id = ProductColor.objects.get(product_id = product_id, color_id = color_id)
여기에 담기는 값은 id가 아닌데 변수명이 id면 헷갈립니다. 수정해주세요~

2022-04-05 06:50 UTC, jamessoun93 commented on carts/views.py
> +                return JsonResponse({'message' : 'Quantity cannot be more than inventory'}, status=400)
이런 부분은 validate_quantity 라는 메소드를 생성해서 분리해주시면 보다 깔끔해지겠네요.

2022-04-05 06:50 UTC, jamessoun93 commented on carts/views.py
> +            cart.save()
이부분은 장고에서 제공하는 `get_or_create()` 메소드로 훨씬 깔끔하게 만들어줄 수 있습니다. 적용해보세요!

2022-04-05 06:50 UTC, jamessoun93 commented on carts/views.py
> +            return JsonResponse({'message' : 'Cart upgraded'}, status=200)
```suggestion
            return JsonResponse({'message' : 'Cart updated'}, status=200)
```

2022-04-05 06:50 UTC, jamessoun93 commented on carts/views.py
> +            return JsonResponse({'message' : 'Cart does not exist'}, status=401)
- 카트에 아무것도 안담아서 빈 카트인 상태는 이렇게 문제의 상황이 아니라서 이렇게 까지 JsonResponse를 따로 반환해주실 필요가 없습니다. (그냥 빈 리스트를 반환해주면 되겠죠?)
- 401은 이 상황에 어울리지 않는 status code 입니다.

2022-04-05 06:50 UTC, jamessoun93 commented on carts/views.py
> +            cart_id   = request.GET.get('id')
해당 요청에는 특정 resource 지정이 가능한 부분이니 query parameter보다 path parameter를 사용해주시면 됩니다.

2022-04-05 06:50 UTC, jamessoun93 commented on carts/views.py
> +            cart          = Cart.objects.get(user = user, id = cart_id)
위에서 가져왔는데 또 가져오네요?

2022-04-05 06:50 UTC, jamessoun93 commented on carts/views.py
> +                'message' : 'Quantity changed',
메세지는 불필요합니다.

2022-04-05 06:50 UTC, jamessoun93 commented on carts/views.py
> +                cart.delete()
반복문을 돌면서 하나하나 처리해주는방식보다 한번에 찾아서 한번에 지워주는 방식이 지우고 싶은 리소스가 많아지면 많아질수록 더 효율적이겠죠?

Hint: `__in`을 사용해보세요.

2022-04-05 09:42 UTC, angrybirdpark commented on carts/views.py
> +            product_color_id = ProductColor.objects.get(product_id = product_id, color_id = color_id)
product_color_id > product_color로 수정완료했습니다!

2022-04-05 09:42 UTC, angrybirdpark commented on carts/views.py
> +                return JsonResponse({'message' : 'Quantity cannot be more than inventory'}, status=400)
carts/validator.py 생성해서 validate_quantity 메소드로 적용했습니다.

2022-04-05 09:43 UTC, angrybirdpark commented on carts/views.py
> +            cart.save()
get_or_create로 적용완료했습니다.

2022-04-05 09:43 UTC, angrybirdpark commented on carts/views.py
> +            return JsonResponse({'message' : 'Cart upgraded'}, status=200)
Cart updated로 변경완료했습니다.

2022-04-05 09:44 UTC, angrybirdpark commented on carts/views.py
> +            return JsonResponse({'message' : 'Cart does not exist'}, status=401)
'result' : []로 수정했습니다.
status code의 경우, not found 의미인 404로 수정했습니다.

2022-04-05 09:44 UTC, angrybirdpark commented on carts/views.py
> +            cart_id   = request.GET.get('id')
path parameter로 변경완료했습니다.

2022-04-05 09:44 UTC, angrybirdpark commented on carts/views.py
> +            cart          = Cart.objects.get(user = user, id = cart_id)
하나로 통합해서 수정완료했습니다..!

2022-04-05 09:44 UTC, angrybirdpark commented on carts/views.py
> +                'message' : 'Quantity changed',
키값에 메세지를 삭제하고 변경한 퀀티티만 표시할 수 있게 수정했습니다.

2022-04-05 09:45 UTC, angrybirdpark commented on carts/views.py
> +                cart.delete()
filter에 id__in을 적용해서 수정완료했습니다..!
__in으로 하니까 훨씬 깔끔해져서 이런 특정 조건을 거는 부분에 대해서 더 공부하도록 하겠습니다. 감사합니다!

2022-04-05 09:45 UTC, angrybirdpark commented
피드백 주신 부분 모두 수정 완료했습니다..! 다시 확인 부탁드립니다 멘토님!

2022-04-05 16:31 UTC, angrybirdpark commented
이전에 올려드렸던 PR에선, 앞 부분에서 quantity에 대한 validate가 모두 진행되다보니
업데이트된 quantity와 inventory(재고)를 비교하는 validate가 존재하지 않았고, 이 부분에서 오류가 발생하는 걸 확인했습니다.
그래서 quantity가 더해진 이후 총 수량의 validate를 추가하여 커밋한 뒤 올려드립니다..!

2022-04-06 01:44 UTC, jamessoun93 requested changes

2022-04-06 01:44 UTC, jamessoun93 commented on carts/validator.py
> +        raise ValidationError('Quantity cannot be more than inventory')
둘다 수량에 대한 유효성검사이면서 validation 에러를 던져주니 따로 호출하지말고 한번에 처리하면 좋겠네요.

2022-04-06 01:44 UTC, jamessoun93 commented on carts/views.py
> +                return JsonResponse({'message' : 'Cart updated'}, status=200)
굳이 메세지는 필요없어보이네요.

2022-04-06 08:46 UTC, jamessoun93 approved these changes

2022-04-06 08:46 UTC, merged